### ISSUE TITLE
Help testing against edge resque

### ISSUE THREAD

**Issue by steveklabnik** [fphilipe/resque-async_deliver#1]
Hey there! 

I'm gearing up to work on Resque 2.0, and I'd like to coordinate better with plugin authors to make sure stuff doesn't break.

I'd like to know a few things:
1. Can I do something to help get you testing against edge Resque?
2. Are you monkey-patching anything in Resque currently? Can 2.0 expose an API to help you not have to do that any more?
3. Do you need any help in bringing your plugin up-to-date with the latest Resque?

Thanks!

Related: https://github.com/defunkt/resque/issues/880

**Comment by fphilipe** [comment]
Hey @steveklabnik, thanks for stopping by. Appreciate your effort!
1. I saw in the README that the jobs now use a `JobClass#work` method. But in the code I still see the old `JobClass.perform` class method. Is the new instance method preferred? Also, did specifying the queue change somehow or is it still the same?
2. Not monkey patching anything. I only rely on `Resque.inline?` which still seems to work.
3. I ran the specs and everything was green. Might work straight out of the box. So, the only point I'm not sure are the ones discussed in 1.

**Comment by steveklabnik** [comment]
1. As it says at the top of the README, 

> Also, this README is written first, so lots of things in here may not work the exact way that they say they might here. Yay 2.0!

So, yes, at the moment, it's mostly the same. The API will change to some degree, though.

Other than that, awesome. `#inline` isn't going away, so you should be good, as long as the eventual interface changes are dealt with. :)

I'll be doing the whole 'beta, rc, final' thing for 2.0, so I will check back in with you upon the beta1. :) Any thoughts/comments in the meantime always welcome.
